packaging_format = 2

id = "tube"
name = "Tube"
description.en = "Youtube-like, video Sharing App"
description.fr = "Application de partage de vidéos de type Youtube"

version = "1.2.0~ynh3"

maintainers = []

[upstream]
license = "MIT"
code = "https://git.mills.io/prologic/tube"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64"]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = false
        amd64.url = "https://git.mills.io/attachments/4873f46b-8056-4b62-890c-49db4ab0a8c9"
        amd64.sha256 = "0986e7c5eb2ad0f00dfd8736688365dadd1bba125c320857845bc86e3afd3ffc"
        arm64.url = "https://git.mills.io/attachments/9a713da8-ae61-434b-87c8-267a2073c2dd"
        arm64.sha256 = "845537d1cd6930fd53c737e8fa58fde0b40228fb78b1fe41b9aaafcfe0b41cba"
        rename = "tube"
        format = "tar.gz"

        autoupdate.strategy = "latest_forgejo_release"
        autoupdate.asset.amd64 = "^tube_.*_linux_amd64.tar.gz$"
        autoupdate.asset.arm64 = "^tube_.*_linux_arm64.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["uploads", "videos"]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "ffmpeg"
