packaging_format = 2

id = "tube"
name = "Tube"
description.en = "Youtube-like, video Sharing App"
description.fr = "Application de partage de vidéos de type Youtube"

version = "1.2.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
demo = "https://tube.mills.io"
code = "https://git.mills.io/prologic/tube"
website = "https://tube.mills.io"

[integration]
yunohost = ">= 11.1.12"
architectures = ["amd64", "arm64"]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "ffmpeg"
